#!/usr/bin/env python3
"""SUPERSEDED by extract_logs2.py -- DO NOT EDIT THIS FILE.

extract_logs2.py segments the same matrices BY TRACK PAIR and says it supersedes
this one. THIS FILE DID NOT SAY IT WAS SUPERSEDED, so the knowledge lived only in
the successor: a reader opening this file first would have found a working script
with no indication it was dead, fixed a bug here, and the fix would never have
reached the file that runs. The two share a five-line main() and would drift
silently. Kept rather than deleted because its output is cited in earlier work.

Original purpose: mine the stage-1 matrix out of the .log.error beside every error file.

PRIVATE — reads real media paths. Never inside the repository.

The fact this rests on
----------------------
There is a `.log.error` next to every one of the 315 error files, 315/315
(measured; vmsam-forensic found this first and I verified it independently).
Each carries the pipeline's own `Multiple delay found with the method 1` line —
the full per-window `(fidelity, offset_points, delay_ms)` matrix.

**So recorded per-window delays already exist for the entire corpus and no
container run is needed to obtain them.** I told dev-1 the opposite earlier —
that delays only exist where a fusion has run, and only id 237 had. That was
wrong and this exists to correct it.

Three caveats that travel with every number this produces
---------------------------------------------------------
1. **These logs were written by an OLDER revision than the one deployed.** Their
   traceback line numbers are `mergeVideo.py:818/:946/:2050`; the same refusal on
   the deployed commit reports `:798/:919/:2057`. The delays measure the MEDIA,
   which has not changed, but the code that measured them is not the code under
   test. Do not attribute them to `db92f0e`.
2. **They come from the integration loop, not the fusion path.** The entry point
   is `main_gestionar_show.process_episode`, not `fusion.run_fusion_job`.
3. **The candidate path in the log is not always today's error path** — some read
   `.../rss/recup/NotRecup/...`. The file has moved since. Pair by episode, and
   treat the logged path as historical.

What the shapes mean, and where each reading comes from
------------------------------------------------------
* a single delay repeated, high fidelity      -> constant offset
* two or more plateaus, high fidelity         -> a STEP. dev-1's 006 shape
* delays monotone and growing along the file  -> candidate speed relation (008)
* delays scattered, sign flipping, fidelity at the floor -> no shared audio

The floor is ~0.5 and not 0: the statistic is mean bit agreement over 32-bit
fingerprints, so **0.50 is chance** (vmsam-forensic's framing, adopted).

**And fidelity alone cannot separate "different content" from "speed mismatch"** —
`docs/AUDIO_SPEED_POLICY.MD` measured uncorrected PAL-against-film pairs at
0.558-0.562, the same floor a no-shared-content pair sits on, because across a
long window a 4.27 % rate difference drifts the signals apart and no single shift
aligns them. That is dev-1's point and it is verified at the source. The separator
is the PATTERN of the delays, not their level.
"""

import json
import os
import re
import sys
from collections import Counter

RUNS = "/home/vmsam/src/VMSAM_HELP_AI/ci/runs"
TRIPLE = re.compile(r"\(([\d.]+),\s*(-?\d+),\s*(-?\d+)\)")
PAIRKEY = re.compile(r"'(\d+-\d+)':\s*\[")
MEANFID = re.compile(r"mean fidelity of ([\d.]+)")
CMDERR = re.compile(r"This cmd is in error")


def parse(path):
    try:
        t = open(path, encoding="utf-8", errors="replace").read()
    except OSError:
        return None
    out = {"has_log": True, "cmd_error": bool(CMDERR.search(t))}
    i = t.find("Multiple delay found")
    if i < 0:
        out["triples"] = None
        m = MEANFID.search(t)
        out["mean_fidelity"] = float(m.group(1)) if m else None
        return out
    seg = t[i:i + 20000]
    out["triples"] = [(float(a), int(b), int(c)) for a, b, c in TRIPLE.findall(seg)]
    out["track_pairs"] = PAIRKEY.findall(seg)
    m = MEANFID.search(t)
    out["mean_fidelity"] = float(m.group(1)) if m else None
    return out


def shape(tr):
    """Classify from the delay pattern, not the fidelity level."""
    if not tr:
        return "no-matrix"
    fids = [x[0] for x in tr]
    dels = [x[2] for x in tr]
    uniq = sorted(set(dels))
    lo, hi = min(fids), max(fids)
    floor = hi < 0.65                      # every window at or near chance
    if len(uniq) == 1:
        return "constant-offset" if not floor else "constant-at-floor"
    flips = sum(1 for a, b in zip(dels, dels[1:])
                if (a > 0) != (b > 0) and a != 0 and b != 0)
    if floor and (len(uniq) >= max(4, len(dels) - 2)):
        return "floor-scatter"             # no shared audio, OR a speed relation
    mono = (all(b >= a for a, b in zip(dels, dels[1:])) or
            all(b <= a for a, b in zip(dels, dels[1:])))
    if mono and len(uniq) >= 4 and not floor:
        return "monotone-drift"            # speed candidate
    if len(uniq) <= 3 and lo > 0.65:
        return "step"                      # dev-1's 006 shape
    return "mixed"


def main():
    rows = json.load(open(f"{RUNS}/sweep-durations.json"))
    out = []
    for r in rows:
        p = r["file_path"] + ".log.error"
        d = parse(p) if os.path.exists(p) else {"has_log": False}
        n = {k: r[k] for k in ("id", "folder_id", "episode_number",
                               "file_path", "master_path")}
        n.update(d or {})
        tr = d.get("triples") if d else None
        n["shape"] = shape(tr) if d else "no-log"
        n["n_windows"] = len(tr) if tr else 0
        n["delays"] = sorted({x[2] for x in tr}) if tr else []
        n["fid_min"] = min((x[0] for x in tr), default=None) if tr else None
        n["fid_max"] = max((x[0] for x in tr), default=None) if tr else None
        out.append(n)

    json.dump(out, open(f"{RUNS}/log-matrices.json", "w"), indent=1)
    print("shape distribution:", file=sys.stderr)
    for k, v in Counter(r["shape"] for r in out).most_common():
        print(f"  {k:<20}: {v}", file=sys.stderr)
    print(f"cmd_error (instrument did not run): "
          f"{sum(1 for r in out if r.get('cmd_error'))}", file=sys.stderr)
    print(f"wrote {RUNS}/log-matrices.json", file=sys.stderr)


if __name__ == "__main__":
    main()
